### ISSUE TITLE
dev cannot be merged into master

### ISSUE THREAD

**Issue by greut** [HIP-infrastructure/Bidsbox#1]
Required for https://github.com/HIP-infrastructure/app-in-browser/pull/106

![Screenshot 2024-10-21 at 08-54-30 Comparing master dev · HIP-infrastructure_Bidsbox](https://github.com/user-attachments/assets/9a68479a-cb21-407a-b15d-f806b3d28b06)

**Comment by floriansipp** [comment]
Should be good now , did a little trimming

**Comment by greut** [comment]
Thanks.
